"""Added adress fild to User Model

Revision ID: a9d000ef0670
Revises: 
Create Date: 2025-02-27 11:31:47.297531

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a9d000ef0670'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.alter_column('content',
        existing_type=mysql.VARCHAR(length=300),
        type_=sa.String(length=200),
        existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=False))
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('address')

    with op.batch_alter_table('boards', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=300),
               existing_nullable=True)

    # ### end Alembic commands ###
